// SABRA! — Tzabi (צבי) the walking sabra fruit. Player sprites, 16×24, facing RIGHT.
// !יאללה צבי — Yalla Tzabi! A prickly pear in sunglasses, flip-flops and a gold chain,
// spitting garinim at anyone who looks at him funny.
//
// Everything below composes to plain string-art frames (see src/engine/sprite.js):
// a hand-drawn body (rows 0-17) + hand-placed skinny legs and kaf-kafim (rows 18-23),
// with squash / stretch / lean transforms for readable animation at 1x.

const W = 16, H = 24;

// ---------------------------------------------------------------- palette
const PAL = {
  k: '#101a12', // outline (near-black green)
  d: '#2c7a3a', // dark green (shadow side, legs)
  g: '#48a64a', // mid green
  l: '#7fd15e', // light green (lit side)
  h: '#c5f26e', // highlight (yellow-green)
  p: '#f3f0c6', // pale spines / areoles
  o: '#f08a24', // sabra flower (orange)
  Y: '#ffd93b', // flower center / chain pendant (bright gold)
  y: '#e0a72a', // gold chain
  G: '#22203a', // sunglasses lens
  b: '#6ea8ff', // lens glint
  w: '#ffffff', // teeth, kaf-kaf sole, eyes, speed lines
  m: '#c9313a', // mouth interior
  f: '#2f6fe0', // kaf-kaf (flip-flop) blue
};

// ---------------------------------------------------------------- body (17 rows × 16)
// Flower on top, chunky sunglasses, cheeky grin, gold chain, spines poking out.
const BODY = [
  '........koo.....', // 0  flower tip
  '.......koYok....', // 1  flower
  '......kkkkok....', // 2  crown
  '.....klhhlk.....', // 3
  '...pkgllhhlkp...', // 4  spines
  '...kdgplhlllk...', // 5
  '..pkkGbGkGbGG...', // 6  sunglasses (arm + two lenses, glints)
  '.pkdgGGGkGGGGG..', // 7  sunglasses wrap around the head
  '..kdgpgllllllkp.', // 8  cheeks
  '..kdgggglllllk..', // 9
  '.pkdggkwwwwwwk..', // 10 grin — teeth
  '..kdgggkmmmmmk..', // 11 grin — mouth
  '..kdggggkkkkkkp.', // 12 grin — lower lip
  '..pkygpggggyk...', // 13 gold chain
  '...kdyyyyyygk...', // 14 gold chain
  '...pkddgYggkp...', // 15 pendant
  '.....kddggk.....', // 16 (bottom ink row is generated by outline())
];

// ---------------------------------------------------------------- face patches (applied on BODY before transforms)
// Each patch is [rows, x, y] — fully opaque so it overwrites the default grin/eyes.
const MOUTH_O = [[ // puckered "pfff" wind-up
  'gglkkklk',
  'ggkmmmkk',
  'gglkkklk',
], 6, 10];
const MOUTH_WIDE = [[ // full-throated PTOO
  'gkkkkkkk',
  'gkmwmmmk',
  'gkkkkkkk',
], 6, 10];
const MOUTH_WAVY = [[ // "oy va voy" wobble
  'gglklklk',
  'ggklklkk',
  'gglllllk',
], 6, 10];
// sunglasses knocked down a row → surprised eyes revealed
const EYES_OUT = [[
  'dwwlhwwlk', // row 5 : eye whites
  'gwkllwklk', // row 6 : pupils
  'gGGGkGGGGG', // row 7 : glasses (unchanged)
  'gGGGkGGGGG', // row 8 : glasses slid down
], 4, 5];

// ---------------------------------------------------------------- helpers
const blank = () => Array.from({ length: H }, () => '.'.repeat(W));
function put(rows, y, x, ch) {
  if (y < 0 || y >= rows.length || x < 0 || x >= W) return;
  rows[y] = rows[y].slice(0, x) + ch + rows[y].slice(x + 1);
}
function blit(rows, src, dx, dy) {
  src.forEach((r, y) => { for (let x = 0; x < r.length; x++) if (r[x] !== '.') put(rows, y + dy, x + dx, r[x]); });
}
function body(...patches) {
  const rows = BODY.slice();
  for (const [p, x, y] of patches) blit(rows, p, x, y);
  return rows;
}
// Squash: 1 wider (duplicate the 2 centre columns) and 1 shorter (drop a cheek row).
const widen = (rows) => rows.map((r) => r.slice(1, 8) + r[7] + r[8] + r.slice(8, 15));
const squash = (rows) => widen(rows).filter((_, i) => i !== 9);
// Stretch: 1 narrower (drop centre column) and 1 taller (duplicate a cheek row).
// drop one centre column per row — never an outline 'k' (prefer the glint / a fill pixel)
const narrow = (rows) => rows.map((r) => { const c = (r[6] === 'b' || r[7] === 'k') ? 6 : 7; return r.slice(0, c) + r.slice(c + 1) + '.'; });
const stretch = (rows) => { const n = narrow(rows); return [...n.slice(0, 10), n[9], ...n.slice(10)]; };
// Lean: shift the top rows [0..r1] right by 1 (Tzabi charging forward).
const lean = (rows, r1 = 9) => rows.map((r, i) => (i <= r1 ? '.' + r.slice(0, W - 1) : r));

// legs: list of [row, col] pixels; feet: kaf-kaf with toe strap at x+3
const leg = (rows, pts) => { for (const [y, x] of pts) put(rows, y, x, 'd'); };
const foot = (rows, y, x) => blit(rows, ['kffkfk', 'kwwwwk'], x, y);

// Full 1-px ink outline: every transparent pixel 4-adjacent to a painted pixel becomes 'k'.
// Keeps Tzabi readable against green awnings / produce (shuk) — the classic pixel-art silhouette move.
function outline(rows) {
  const src = rows.slice();
  const at = (y, x) => (y < 0 || y >= H || x < 0 || x >= W ? '.' : src[y][x]);
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
    if (src[y][x] !== '.') continue;
    if (at(y - 1, x) !== '.' || at(y + 1, x) !== '.' || at(y, x - 1) !== '.' || at(y, x + 1) !== '.') put(rows, y, x, 'k');
  }
  return rows;
}

// assemble one 16×24 frame: body rows at vertical offset dy (+1 so the flower gets a top outline row),
// then legs/feet, then the ink outline, then non-outlined extras (speed lines, bling).
function frame(bodyRows, dy, legsFn, extra) {
  const rows = blank();
  blit(rows, bodyRows, 0, dy + 1);
  legsFn(rows);
  outline(rows);
  if (extra) extra(rows);
  return rows;
}

// ---------------------------------------------------------------- leg poses (absolute rows)
const LEGS = {
  // relaxed splayed stance — "מה נסגר?"
  idle: (r) => {
    leg(r, [[18, 6], [19, 5], [20, 4], [21, 4]]); foot(r, 22, 1);
    leg(r, [[18, 9], [19, 10], [20, 11], [21, 12]]); foot(r, 22, 9);
  },
  idleDown: (r) => { // body 1px lower (exhale)
    leg(r, [[19, 6], [20, 5], [21, 4]]); foot(r, 22, 1);
    leg(r, [[19, 9], [20, 10], [21, 11]]); foot(r, 22, 9);
  },
  // run cycle
  contactA: (r) => { // wide stride, both feet down
    leg(r, [[18, 6], [19, 5], [20, 4], [21, 3]]); foot(r, 22, 0);
    leg(r, [[18, 9], [19, 10], [20, 11], [21, 12]]); foot(r, 22, 9);
  },
  recoilA: (r) => { // body +1, front leg planted, back foot lifting
    leg(r, [[19, 9], [20, 10], [21, 10]]); foot(r, 22, 7);
    leg(r, [[19, 5], [20, 4]]); foot(r, 21, 0);
  },
  passA: (r) => { // front foot kicks forward in the air
    leg(r, [[18, 9], [19, 10]]); foot(r, 20, 8);
    leg(r, [[18, 6], [19, 5], [20, 4], [21, 3]]); foot(r, 22, 0);
  },
  contactB: (r) => { // slightly narrower stride
    leg(r, [[18, 6], [19, 5], [20, 4], [21, 4]]); foot(r, 22, 1);
    leg(r, [[18, 9], [19, 10], [20, 11], [21, 11]]); foot(r, 22, 8);
  },
  recoilB: (r) => {
    leg(r, [[19, 9], [20, 9], [21, 10]]); foot(r, 22, 7);
    leg(r, [[19, 5], [20, 4]]); foot(r, 21, 0);
  },
  passB: (r) => {
    leg(r, [[18, 8], [19, 9]]); foot(r, 20, 7);
    leg(r, [[18, 6], [19, 5], [20, 4], [21, 4]]); foot(r, 22, 1);
  },
  // jump: stretched body ends at row 18 — legs start row 19
  launch: (r) => {
    leg(r, [[19, 6], [20, 5], [21, 5]]); foot(r, 22, 2);
    leg(r, [[19, 9]]); foot(r, 20, 7);
  },
  tuck: (r) => { // knees up at the apex
    leg(r, [[18, 6], [19, 5]]); foot(r, 20, 1);
    leg(r, [[18, 9], [19, 10]]); foot(r, 20, 8);
  },
  // fall: squashed body (bottom row 17), legs flailing wide
  flailA: (r) => {
    leg(r, [[18, 5], [19, 4], [20, 3]]); foot(r, 21, 0);
    leg(r, [[18, 10], [19, 11], [20, 12]]); foot(r, 21, 10);
  },
  flailB: (r) => {
    leg(r, [[18, 5], [19, 4], [20, 3], [21, 3]]); foot(r, 22, 0);
    leg(r, [[18, 10], [19, 11], [20, 12]]); foot(r, 21, 10);
  },
  splat: (r) => { // hurt, knocked into a wide squat
    leg(r, [[18, 5], [19, 4], [20, 3], [21, 3]]); foot(r, 22, 0);
    leg(r, [[18, 10], [19, 11], [20, 12], [21, 13]]); foot(r, 22, 10);
  },
};

// speed lines behind Tzabi for the dash
const speedLines = (r) => { for (const y of [5, 9, 14]) { put(r, y, 0, 'w'); put(r, y, 1, 'w'); } };

// ---------------------------------------------------------------- sprite defs
const def = (fps, frames) => ({ w: W, h: H, fps, palette: PAL, frames });

const PLAYER_IDLE = def(3, [
  frame(body(), 0, LEGS.idle),
  frame(body(), 1, LEGS.idleDown),
  frame(body(), 0, LEGS.idle, (r) => put(r, 15, 8, 'w')), // pendant bling
]);

const PLAYER_RUN = def(12, [
  frame(body(), 0, LEGS.contactA),
  frame(body(), 1, LEGS.recoilA),
  frame(body(), 0, LEGS.passA),
  frame(body(), 0, LEGS.contactB),
  frame(body(), 1, LEGS.recoilB),
  frame(body(), 0, LEGS.passB),
]);

const PLAYER_JUMP = def(8, [
  frame(stretch(body()), 0, LEGS.launch),
  frame(body(), 0, LEGS.tuck),
]);

const PLAYER_FALL = def(8, [
  frame(squash(body()), 1, LEGS.flailA),
  frame(squash(body()), 1, LEGS.flailB),
]);

const PLAYER_SPIT = def(12, [
  frame(widen(body(MOUTH_O)), 0, LEGS.idle),          // cheeks puff
  frame(lean(body(MOUTH_WIDE)), 0, LEGS.contactB),    // PTOO!
  frame(body(), 0, LEGS.idle),                        // back to the grin
]);

const PLAYER_HURT = def(8, [
  frame(body(EYES_OUT, MOUTH_WAVY), 0, LEGS.idle),
  frame(squash(body(EYES_OUT, MOUTH_WAVY)), 1, LEGS.splat),
]);

const PLAYER_DASH = def(12, [
  frame(lean(body()), 0, LEGS.contactA),
  frame(lean(body()), 0, LEGS.contactB, speedLines),
]);

// spinning garin (sunflower seed): black with white stripes
const SEED = {
  w: 4, h: 4, fps: 12,
  palette: { k: '#1a1a1a', w: '#f5f0e6' },
  frames: [
    ['.kk.', 'kwkk', 'kkwk', '.kk.'],
    ['.kk.', 'kkwk', 'kwkk', '.kk.'],
  ],
};

export default { PLAYER_IDLE, PLAYER_RUN, PLAYER_JUMP, PLAYER_FALL, PLAYER_SPIT, PLAYER_HURT, PLAYER_DASH, SEED };
