// SABRA! — Level 1: חוף תל אביב · Tel Aviv Beach at sunrise.
// Map: 200x16 tiles (3200x256 px). Legend: '#' ground, '=' one-way platform, '^' jellyfish water (hazard).
// Entities' y = FEET, always on top of a solid tile (row*16). Generated grid, hand-designed layout.
//
// Flow (tile columns): 0-24 boardwalk & tutorial step · 25-52 dunes + shallow sand pits · 53-111 matkot,
// platform stairs, dune mesa (secret krembo above), matkot duel over a lethal gap (bamba on a boardwalk above) ·
// 112-146 jellyfish water: boardwalk hopping over the sea, sandbars to recover · 147-181 Frishman beach,
// cat gauntlet, climb, lethal gap · 182-199 promenade with a parking inspector, then the apartment door.

export default {
  id: 'telaviv', name: 'חוף תל אביב', nameEn: 'Tel Aviv Beach', theme: 'TELAVIV',
  intro: ['בוקר טוב תל אביב! השמש כבר בשבע בבוקר', 'Good morning Tel Aviv! The sun is out at 7am already'],
  tileSize: 16,
  map: [
    '........................................................................................................................................................................................................',
    '........................................................................................................................................................................................................',
    '........................................................................................................................................................................................................',
    '....................................................................................===.................................................................................................................',
    '........................................................................................................................................................................................................',
    '...............................................................................===......................................................................................................................',
    '........................................................................................................................................................................................................',
    '..........................................................................====..........................................................................................................................',
    '........................................................................................................................................................................................................',
    '.....................................................................====......##########..........................................................................===..................................',
    '...............................................................................##########.............................====.......====........====.......................................................',
    '................................................................====...........##########....======.............====........===........====............................######...######..................',
    '.....................######....................................................##########.....................##.................................##..............############...######.............#####',
    '##############################..#################...###########################################...##############.....#.....#....#.....#.....#....############################...########################',
    '##############################..#################...###########################################^^^##############^^^^^#^^^^^#^^^^#^^^^^#^^^^^#^^^^############################^^^########################',
    '########################################################################################################################################################################################################',
  ],
  legend: { '#': 'ground', '=': 'platform', '^': 'hazard' },
  spawn: { x: 40, y: 208 },
  exit: { x: 3160, y: 192 },
  entities: [
    { type: 'prop', sprite: 'LAMP', x: 24, y: 208 },
    { type: 'sign', x: 72, y: 208, text: ['ברוכים הבאים לתל אביב. בבקשה לא להאכיל את היונים', 'Welcome to Tel Aviv — please don\'t feed the pigeons'] },
    { type: 'prop', sprite: 'BENCH', x: 136, y: 208 },
    { type: 'pigeon', x: 168, y: 208 },
    { type: 'pigeon', x: 232, y: 208 },
    { type: 'shekel', x: 200, y: 192 },
    { type: 'shekel', x: 232, y: 192 },
    { type: 'shekel', x: 264, y: 192 },
    { type: 'shekel', x: 312, y: 176 },
    { type: 'shekel', x: 328, y: 160 },
    { type: 'shekel', x: 344, y: 160 },
    { type: 'prop', sprite: 'BARREL', x: 392, y: 192 },
    { type: 'prop', sprite: 'UMBRELLA', x: 440, y: 208 },
    { type: 'shekel', x: 472, y: 176 },
    { type: 'shekel', x: 488, y: 160 },
    { type: 'shekel', x: 504, y: 160 },
    { type: 'shekel', x: 520, y: 176 },
    { type: 'sign', x: 536, y: 208, text: ['המציל: אין מציל', 'Lifeguard: no lifeguard'] },
    { type: 'prop', sprite: 'LIFEGUARD_TOWER', x: 568, y: 208 },
    { type: 'tourist', x: 616, y: 208 },
    { type: 'prop', sprite: 'PALM', x: 664, y: 208 },
    { type: 'pigeon', x: 680, y: 208 },
    { type: 'pigeon', x: 712, y: 208 },
    { type: 'prop', sprite: 'UMBRELLA', x: 728, y: 208 },
    { type: 'prop', sprite: 'BENCH', x: 760, y: 208 },
    { type: 'cat', x: 760, y: 208 },
    { type: 'shekel', x: 776, y: 176 },
    { type: 'shekel', x: 792, y: 160 },
    { type: 'shekel', x: 808, y: 160 },
    { type: 'shekel', x: 824, y: 160 },
    { type: 'shekel', x: 840, y: 176 },
    { type: 'checkpoint', x: 872, y: 208 },
    { type: 'sign', x: 920, y: 208, text: ['מטקות: הספורט הלאומי. הכדור תמיד עובר ליד הראש', 'Matkot: the national sport. The ball always passes by your head'] },
    { type: 'matkot', x: 984, y: 208 },
    { type: 'shekel', x: 1048, y: 160 },
    { type: 'shekel', x: 1064, y: 160 },
    { type: 'shekel', x: 1128, y: 128 },
    { type: 'shekel', x: 1144, y: 128 },
    { type: 'shekel', x: 1208, y: 96 },
    { type: 'shekel', x: 1224, y: 96 },
    { type: 'falafel', x: 1160, y: 128 },
    { type: 'shekel', x: 1288, y: 64 },
    { type: 'krembo', x: 1368, y: 48 },
    { type: 'sign', x: 1304, y: 144, text: ['שמש בשבע בבוקר? מי אישר את זה', 'Sun at 7am? Who approved this'] },
    { type: 'pigeon', x: 1352, y: 144 },
    { type: 'prop', sprite: 'UMBRELLA', x: 1400, y: 144 },
    { type: 'shekel', x: 1336, y: 128 },
    { type: 'shekel', x: 1368, y: 128 },
    { type: 'shekel', x: 1400, y: 128 },
    { type: 'matkot', x: 1464, y: 208 },
    { type: 'bamba', x: 1544, y: 160 },
    { type: 'matkot', x: 1640, y: 208 },
    { type: 'prop', sprite: 'UMBRELLA', x: 1688, y: 208 },
    { type: 'checkpoint', x: 1704, y: 208 },
    { type: 'hummus', x: 1736, y: 192 },
    { type: 'prop', sprite: 'LAMP', x: 1768, y: 192 },
    { type: 'sign', x: 1816, y: 176, text: ['מדוזות! ים סגור. גם מחר', 'Jellyfish! Sea closed. Tomorrow too'] },
    { type: 'jellyfish', x: 1860, y: 204, amp: 10 },
    { type: 'jellyfish', x: 1928, y: 216, amp: 6 },
    { type: 'shekel', x: 1864, y: 160 },
    { type: 'shekel', x: 1880, y: 144 },
    { type: 'shekel', x: 1960, y: 144 },
    { type: 'shekel', x: 1976, y: 144 },
    { type: 'jellyfish', x: 2036, y: 204, amp: 10 },
    { type: 'shekel', x: 2040, y: 160 },
    { type: 'shekel', x: 2056, y: 160 },
    { type: 'sign', x: 2104, y: 160, text: ['אין חניה. גם לא בים', 'No parking. Not even in the sea'] },
    { type: 'shekel', x: 2136, y: 144 },
    { type: 'shekel', x: 2152, y: 144 },
    { type: 'falafel', x: 2200, y: 160 },
    { type: 'pigeon', x: 2184, y: 176 },
    { type: 'jellyfish', x: 2228, y: 204, amp: 10 },
    { type: 'jellyfish', x: 2296, y: 216, amp: 6 },
    { type: 'shekel', x: 2232, y: 160 },
    { type: 'shekel', x: 2248, y: 144 },
    { type: 'checkpoint', x: 2408, y: 208 },
    { type: 'prop', sprite: 'UMBRELLA', x: 2440, y: 208 },
    { type: 'sign', x: 2472, y: 208, text: ['החתיכים של חוף פרישמן. אל תבהה', 'The Frishman beach cool guys. Don\'t stare'] },
    { type: 'prop', sprite: 'BENCH', x: 2504, y: 208 },
    { type: 'cat', x: 2536, y: 208 },
    { type: 'pigeon', x: 2552, y: 208 },
    { type: 'pigeon', x: 2568, y: 208 },
    { type: 'bamba', x: 2632, y: 128 },
    { type: 'cat', x: 2728, y: 176 },
    { type: 'shekel', x: 2776, y: 144 },
    { type: 'shekel', x: 2792, y: 128 },
    { type: 'shekel', x: 2808, y: 144 },
    { type: 'sign', x: 2856, y: 176, text: ['חניה: 30 ₪ לשעה. הים: חינם. בינתיים', 'Parking: 30 NIS an hour. The sea: free. For now'] },
    { type: 'prop', sprite: 'PALM', x: 2888, y: 176 },
    { type: 'prop', sprite: 'BENCH', x: 2952, y: 208 },
    { type: 'pakid', x: 3000, y: 208 },
    { type: 'prop', sprite: 'LAMP', x: 3032, y: 208 },
    { type: 'cat', x: 3064, y: 208 },
    { type: 'sign', x: 3096, y: 208, text: ['דירה בתל אביב: 4 מ״ר, 9,000 ₪. נוף לים אם עומדים על כיסא', 'Tel Aviv apartment: 4 sqm, 9,000 NIS. Sea view if you stand on a chair'] },
    { type: 'prop', sprite: 'PALM', x: 3112, y: 208 },
    { type: 'pigeon', x: 3160, y: 192 },
    { type: 'shekel', x: 1512, y: 160 },
    { type: 'shekel', x: 1528, y: 144 },
    { type: 'shekel', x: 1560, y: 144 },
    { type: 'shekel', x: 1576, y: 160 },
  ],
  quips: [
    ['שמש בשבע בבוקר. אין מצב', 'Sun at 7am. No way'],
    ['חניה בתל אביב זה לא מקום, זה מצב נפשי', 'Parking in Tel Aviv isn\'t a place, it\'s a state of mind'],
    ['המציל אמר שאין מציל', 'The lifeguard said there\'s no lifeguard'],
    ['ים סגור בגלל מדוזות. גם החיים', 'Sea closed due to jellyfish. Life too'],
    ['החתיכים של פרישמן מתאמנים על מטקות מאז 1994', 'The Frishman cool guys have been training matkot since 1994'],
    ['תייר שאל איפה החוף. הוא עמד עליו', 'A tourist asked where the beach is. He was standing on it'],
    ['היונים פה משלמות יותר שכר דירה ממך', 'The pigeons here pay more rent than you'],
    ['פוק. פוק. פוק. ככה נשמע קיץ', 'Pok. Pok. Pok. That\'s the sound of summer'],
    ['החתול מתחת לכיסא הוא בעל הבית', 'The cat under the chair is the landlord'],
    ['אין מקום לשים מגבת. יש מקום למדוזה', 'No room for a towel. Plenty of room for a jellyfish'],
    ['הכפכפים הם נעלי עבודה', 'Flip-flops are work shoes'],
    ['הפקח לא ישן. הפקח לא אוכל. הפקח רק רושם', 'The inspector doesn\'t sleep. Doesn\'t eat. Only writes tickets'],
  ],
};
