// SABRA! — Level 4: המדבר וים המלח · The Negev desert and the Dead Sea.
// Map: 210x16 tiles (3360x256 px). Legend: '#' sandstone ground, '=' one-way ledge, 'W' sheer mesa face,
// '^' cactus spikes (hazard), '~' Dead Sea water (non-solid, low-gravity float zone).
// Entities' y = FEET, always on top of a solid tile (row*16); pickups' y = bottom edge. Hand-designed layout,
// grid generated from primitives (tools-free, no build step) and frozen here as literal rows.
//
// Flow (tile columns): 0-21 spawn plateau, step + shallow pit tutorial · 22-53 cactus hop, cat, platform stairs
// up a sandstone mesa (falafel, Ramon sign) · 54-77 canyon crossed on three slow camels (one mid-canyon pillar) ·
// 78-99 pakid checkpoint booth under an awning (bamba on the roof), cactus field with a high ledge ·
// 100-156 the Dead Sea: climb UP to the lowest point on earth (the beach sits one tile under the water line so
// you can always climb out), 34 tiles of low-gravity water with shekels near the surface, hummus + shekels deep in
// the mud, mud pillars to rest on, mosquitoes instead of pigeons, muddy tourist, bedouin tent + tea sign ·
// 157-209 gap, cactus with a high route, a pit that leads into a secret cave (krembo), mesa 2 with a savta,
// the shelf down to a second pakid, a final camel gap and the exit.
// Lethal drops (no tiles at all): cols 56-60, 67-70, 73-77, 163-165, 196-199. Every other pit has a floor.

export default {
  id: 'negev', name: 'המדבר וים המלח', nameEn: 'Negev & the Dead Sea', theme: 'NEGEV',
  intro: ['המדבר וים המלח. תביא מים. הרבה מים.', 'The desert and the Dead Sea. Bring water. Lots of water.'],
  tileSize: 16,
  map: [
    '..................................................................................................................................................................................................................',
    '..................................................................................................................................................................................................................',
    '..................................................................................................................................................................................................................',
    '..................................................................................................................................................................................................................',
    '..................................................................................................................................................................................................................',
    '..................................................................................................................................................................................................................',
    '..................................................................................................................................................................................................................',
    '..................................................................................................................................................................................................................',
    '..........................................########................................................................................................................................................................',
    '.......................................==.W######W..........................................................................................................................###############.......................',
    '..........................................W######W..............................=====.......................~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~..............................W#############W.......................',
    '##..................................==....W######W.....................##..................==...........####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~###########...............===.W#############W####...................',
    '#W..............####......................W######W.....................WW......#......................######~~~~~~~~##~~~~~~~~##~~~~~~##~~~~~~#############.................W#############W####...................',
    '####################..#####^^###########################.....######....WW.....#########^^##^^#^^^###########~~~~~~~~##~~~~~~~~##~~~~~~##~~~~~~#####################...#^^#............##############....##########',
    '####################..##################################.....######....WW.....##############################~~~~~~~~##~~~~~~~~##~~~~~~##~~~~~~#####################...####............##############....##########',
    '########################################################.....######....##.....#####################################################################################...##############################....##########',
  ],
  legend: { '#': 'ground', '=': 'platform', 'W': 'wall', '^': 'hazard', '~': 'water' },
  spawn: { x: 40, y: 208 },
  exit: { x: 3304, y: 208 },
  entities: [
    { type: "prop", sprite: "SIGN_NEGEV", x: 56, y: 208 },
    { type: "sign", x: 88, y: 208, text: ["אין קליטה. גם לא לפני זה.", "No signal. Wasn't before either."] },
    { type: "prop", sprite: "CACTUS", x: 136, y: 208 },
    { type: "shekel", x: 184, y: 192 },
    { type: "shekel", x: 200, y: 192 },
    { type: "shekel", x: 216, y: 192 },
    { type: "shekel", x: 232, y: 192 },
    { type: "shekel", x: 280, y: 176 },
    { type: "prop", sprite: "BARREL", x: 312, y: 192 },
    { type: "sign", x: 392, y: 208, text: ["קקטוס: לא מחבקים. גם אם הוא נראה בודד", "Cactus: no hugs. Even if it looks lonely"] },
    { type: "prop", sprite: "CACTUS", x: 504, y: 208 },
    { type: "cat", x: 536, y: 208 },
    { type: "shekel", x: 584, y: 160 },
    { type: "shekel", x: 600, y: 160 },
    { type: "shekel", x: 632, y: 128 },
    { type: "shekel", x: 648, y: 128 },
    { type: "prop", sprite: "OLIVE_TREE", x: 696, y: 128 },
    { type: "shekel", x: 696, y: 112 },
    { type: "shekel", x: 728, y: 112 },
    { type: "shekel", x: 760, y: 112 },
    { type: "falafel", x: 712, y: 128 },
    { type: "cat", x: 744, y: 128 },
    { type: "sign", x: 776, y: 128, text: ["מכתש רמון ← 400 ק\"מ (מרגיש ככה)", "Ramon crater 400km (feels like it)"] },
    { type: "checkpoint", x: 840, y: 208 },
    { type: "prop", sprite: "CACTUS", x: 872, y: 208 },
    { type: "camel", x: 936, y: 208, patrol: 40 },
    { type: "shekel", x: 920, y: 176 },
    { type: "shekel", x: 936, y: 160 },
    { type: "shekel", x: 952, y: 176 },
    { type: "prop", sprite: "OLIVE_TREE", x: 1016, y: 208 },
    { type: "camel", x: 1104, y: 208, patrol: 28 },
    { type: "shekel", x: 1144, y: 160 },
    { type: "shekel", x: 1160, y: 160 },
    { type: "camel", x: 1208, y: 176, patrol: 32 },
    { type: "sign", x: 1256, y: 208, text: ["מחסום. תעודה, אישור, ובעיקר סבלנות", "Checkpoint: ID, permit, and mostly patience"] },
    { type: "prop", sprite: "BARREL", x: 1272, y: 192 },
    { type: "prop", sprite: "TRAFFIC_CONE", x: 1288, y: 208 },
    { type: "pakid", x: 1320, y: 208 },
    { type: "prop", sprite: "TRAFFIC_CONE", x: 1368, y: 208 },
    { type: "shekel", x: 1304, y: 144 },
    { type: "shekel", x: 1336, y: 144 },
    { type: "bamba", x: 1320, y: 160 },
    { type: "shekel", x: 1400, y: 176 },
    { type: "shekel", x: 1416, y: 176 },
    { type: "shekel", x: 1464, y: 160 },
    { type: "shekel", x: 1480, y: 160 },
    { type: "shekel", x: 1528, y: 176 },
    { type: "prop", sprite: "CACTUS", x: 1576, y: 208 },
    { type: "checkpoint", x: 1608, y: 208 },
    { type: "sign", x: 1688, y: 176, text: ["ים המלח: אל תשתה. כן, גם לא \"רק לטעום\"", "Dead Sea: don't drink it. No, not \"just a taste\""] },
    { type: "prop", sprite: "PALM", x: 1720, y: 176 },
    { type: "shekel", x: 1768, y: 176 },
    { type: "shekel", x: 1800, y: 176 },
    { type: "shekel", x: 1832, y: 176 },
    { type: "mosquito", x: 1800, y: 144 },
    { type: "shekel", x: 1928, y: 176 },
    { type: "shekel", x: 1960, y: 176 },
    { type: "shekel", x: 1992, y: 176 },
    { type: "hummus", x: 1944, y: 240 },
    { type: "mosquito", x: 1960, y: 136 },
    { type: "falafel", x: 2024, y: 192 },
    { type: "shekel", x: 2088, y: 240 },
    { type: "shekel", x: 2104, y: 240 },
    { type: "shekel", x: 2120, y: 240 },
    { type: "mosquito", x: 2120, y: 144 },
    { type: "mosquito", x: 2232, y: 152 },
    { type: "sign", x: 2296, y: 176, text: ["הנקודה הנמוכה בעולם. במפה שלנו זה למעלה. אל תשאלו", "Lowest point on Earth. On our map it's up. Don't ask"] },
    { type: "prop", sprite: "PALM", x: 2312, y: 176 },
    { type: "tourist", x: 2344, y: 176, patrol: 32 },
    { type: "prop", sprite: "TENT", x: 2392, y: 176 },
    { type: "sign", x: 2424, y: 176, text: ["תה? שב, שב", "Tea? Sit, sit"] },
    { type: "checkpoint", x: 2440, y: 176 },
    { type: "prop", sprite: "BARREL", x: 2472, y: 192 },
    { type: "prop", sprite: "OLIVE_TREE", x: 2520, y: 208 },
    { type: "cat", x: 2568, y: 208 },
    { type: "shekel", x: 2632, y: 176 },
    { type: "shekel", x: 2680, y: 176 },
    { type: "shekel", x: 2696, y: 176 },
    { type: "shekel", x: 2712, y: 160 },
    { type: "shekel", x: 2728, y: 160 },
    { type: "krembo", x: 2888, y: 240 },
    { type: "prop", sprite: "CACTUS", x: 2792, y: 144 },
    { type: "sign", x: 2824, y: 144, text: ["מערה? איזו מערה. אין פה מערה", "Cave? What cave. There is no cave here"] },
    { type: "shekel", x: 2856, y: 128 },
    { type: "shekel", x: 2888, y: 128 },
    { type: "savta", x: 2920, y: 144 },
    { type: "prop", sprite: "BARREL", x: 2952, y: 144 },
    { type: "bamba", x: 2968, y: 144 },
    { type: "prop", sprite: "CACTUS", x: 3032, y: 176 },
    { type: "checkpoint", x: 3064, y: 208 },
    { type: "pakid", x: 3096, y: 208 },
    { type: "sign", x: 3128, y: 208, text: ["ברוכים הבאים לאילת. סתם. עוד 200 ק\"מ", "Welcome to Eilat. Kidding. 200km to go"] },
    { type: "camel", x: 3168, y: 208, patrol: 32 },
    { type: "shekel", x: 3160, y: 176 },
    { type: "shekel", x: 3176, y: 176 },
    { type: "prop", sprite: "LAMP", x: 3224, y: 208 },
    { type: "shekel", x: 3256, y: 192 },
    { type: "prop", sprite: "OLIVE_TREE", x: 3272, y: 208 },
    { type: "prop", sprite: "CACTUS", x: 3336, y: 208 },
  ],
  quips: [
    ["חם. חם חם. חם.", "Hot. Hot hot. Hot."],
    ["קרם הגנה 50? הבאתי 15 ואופטימיות", "SPF 50? I brought 15 and optimism"],
    ["הבוץ הזה טוב לעור. ככה אמרו לי. ב־1997", "This mud is good for the skin. So I was told. In 1997"],
    ["ים המלח: המקום היחיד שצפים בו בלי מאמץ. כמו בישיבת צוות", "Dead Sea: the only place you float effortlessly. Like in a team meeting"],
    ["הגמל לא ממהר. הגמל אף פעם לא ממהר", "The camel is not in a hurry. The camel is never in a hurry"],
    ["42 מעלות. בצל. איזה צל", "42 degrees. In the shade. What shade"],
    ["אין מים במדבר? יש. ב־12 שקל הבקבוק", "No water in the desert? There is. 12 shekels a bottle"],
    ["שרטת? זה מלח. שרפת? זה מלח. הכל מלח", "Scratched? Salt. Burnt? Salt. Everything is salt"],
    ["יתוש בים המלח. גם הוא לא מבין מה הוא עושה פה", "A mosquito at the Dead Sea. It also has no idea what it's doing here"],
    ["הגב שלי נראה כמו מפת הנגב", "My back looks like a map of the Negev"],
    ["תה של בדואים: כוס אחת = שלוש שעות", "Bedouin tea: one cup = three hours"],
    ["הפקיד אומר שהחום \"לא בתחום סמכותו\"", "The clerk says the heat is \"not his department\""],
  ],
};
