// SABRA! — Level 5: ירושלים העתיקה · Jerusalem Old City at golden hour. Final level.
// Map: 216x16 tiles (3456x256 px). Legend: '#' stone ground, '=' arch ledge (one-way), 'W' Old City wall (solid), '^' hot coals.
// Entities' y = FEET, always on top of a solid tile (row*16). Generated grid, hand-designed layout.
//
// Flow (tile columns): 0-27 Jaffa Gate approach, first arch ledge, first cat · 28-52 cobbled alley: dip, stone wall hop,
// lethal pothole, savta on a balcony · 53-78 shawarma stand with hot coals (ledges above as the safe route) ·
// 79-104 stone stairs up to a rooftop (secret krembo, a guard cat, a view of your aunt) while the alley below is under
// renovation · 105-135 Ministry of Interior queue: three ticket-throwing pakids, a tourist with a map, a bamba over the desk ·
// 136-138 lethal gap · 139-160 the Cat Committee (hummus ledge before it = invincibility run) · 161-187 checkpoint,
// coal gauntlet, second balcony savta, last lethal gap · 188-215 courtyard arena: Savta Rivka hurls kubbeh, three ledges
// to dodge from, the exit door unlocks when she goes to rest.

export default {
  id: 'jerusalem', name: 'ירושלים העתיקה', nameEn: 'Jerusalem Old City', theme: 'JERUSALEM',
  intro: ['ירושלים של זהב. ושל חתולים. ושל סבתא', 'Jerusalem of gold. And of cats. And of Savta'],
  tileSize: 16,
  map: [
    '........................................................................................................................................................................................................................',
    '........................................................................................................................................................................................................................',
    '........................................................................................................................................................................................................................',
    '........................................................................................................................................................................................................................',
    '...................................................................................................==...................................................................................................................',
    '......................................................................................................W.................................................................................................................',
    '............................................................................................===.======..................................................................................................................',
    '........................................................................................................................................................................................................................',
    '........................................................................................===.............................................................................................................................',
    'W.......................................................................................................................................................................................................===............W',
    'W...................................................................................===................................................................................................................................W',
    'W............................................====......................==...................................................................................................==......====...........===.......===.......W',
    'W...................===...........W.===.....................=====..===..........===..............W.......................===.===............===..===..===..........W....===.....==...........W.........................W',
    'W.................................W...............W.............................................WW...................W............W................................W.........................W.........................W',
    '############################..###########...#################^^^####^^^#################################################################...##############################^^^###^^^^######...############################',
    '#########################################...############################################################################################...##############################################...############################',
  ],
  legend: { '#': 'ground', '=': 'platform', 'W': 'wall', '^': 'hazard' },
  spawn: { x: 40, y: 224 },
  exit: { x: 3416, y: 224 },
  entities: [
    { type: 'prop', sprite: 'LAMP', x: 40, y: 224 },
    { type: 'sign', x: 104, y: 224, text: ['ירושלים: 3000 שנה, עדיין בשיפוצים', 'Jerusalem: 3000 years, still under renovation'] },
    { type: 'prop', sprite: 'SIGN_JLM', x: 152, y: 224 },
    { type: 'prop', sprite: 'OLIVE_TREE', x: 216, y: 224 },
    { type: 'pigeon', x: 184, y: 224 },
    { type: 'pigeon', x: 264, y: 224 },
    { type: 'cat', x: 312, y: 224 },
    { type: 'shekel', x: 328, y: 176 },
    { type: 'shekel', x: 344, y: 176 },
    { type: 'shekel', x: 360, y: 176 },
    { type: 'prop', sprite: 'MENORAH', x: 392, y: 224 },
    { type: 'sign', x: 424, y: 224, text: ['חתולים: 1,000,000 / תושבים: פחות', 'Cats: 1,000,000 / residents: fewer'] },
    { type: 'shekel', x: 456, y: 240 },
    { type: 'shekel', x: 472, y: 240 },
    { type: 'prop', sprite: 'BARREL', x: 520, y: 224 },
    { type: 'shekel', x: 584, y: 160 },
    { type: 'shekel', x: 600, y: 160 },
    { type: 'shekel', x: 616, y: 160 },
    { type: 'prop', sprite: 'LAMP', x: 632, y: 224 },
    { type: 'sign', x: 648, y: 224, text: ['זהירות: בור. העירייה יודעת מ-1967', 'Careful: pothole. City Hall has known since 1967'] },
    { type: 'savta', x: 744, y: 176 },
    { type: 'prop', sprite: 'AWNING', x: 760, y: 176 },
    { type: 'cat', x: 792, y: 224 },
    { type: 'pigeon', x: 840, y: 224 },
    { type: 'checkpoint', x: 872, y: 224 },
    { type: 'sign', x: 904, y: 224, text: ['שווארמה: 52 ₪. בלי מה שאתה רוצה', 'Shawarma: 52 NIS. Without whatever you wanted'] },
    { type: 'prop', sprite: 'AWNING', x: 936, y: 224 },
    { type: 'prop', sprite: 'BARREL', x: 952, y: 224 },
    { type: 'shekel', x: 984, y: 160 },
    { type: 'shekel', x: 1000, y: 160 },
    { type: 'shekel', x: 1016, y: 160 },
    { type: 'falafel', x: 1064, y: 208 },
    { type: 'shekel', x: 1096, y: 160 },
    { type: 'shekel', x: 1112, y: 160 },
    { type: 'shekel', x: 1144, y: 144 },
    { type: 'shekel', x: 1160, y: 144 },
    { type: 'prop', sprite: 'BENCH', x: 1192, y: 224 },
    { type: 'pigeon', x: 1208, y: 224 },
    { type: 'pigeon', x: 1240, y: 224 },
    { type: 'prop', sprite: 'LAMP', x: 1256, y: 224 },
    { type: 'shekel', x: 1304, y: 176 },
    { type: 'shekel', x: 1368, y: 144 },
    { type: 'shekel', x: 1432, y: 112 },
    { type: 'shekel', x: 1496, y: 80 },
    { type: 'pigeon', x: 1544, y: 96 },
    { type: 'pigeon', x: 1608, y: 96 },
    { type: 'cat', x: 1576, y: 96 },
    { type: 'krembo', x: 1592, y: 64 },
    { type: 'shekel', x: 1608, y: 48 },
    { type: 'sign', x: 1560, y: 96, text: ['מפה רואים את כל ירושלים. וגם את הדודה שלך', 'From here you can see all of Jerusalem. And your aunt'] },
    { type: 'prop', sprite: 'OLIVE_TREE', x: 1352, y: 224 },
    { type: 'cat', x: 1464, y: 224 },
    { type: 'prop', sprite: 'LAMP', x: 1656, y: 224 },
    { type: 'checkpoint', x: 1704, y: 224 },
    { type: 'sign', x: 1736, y: 224, text: ['משרד הפנים: קח מספר, נתראה בחג', 'Ministry of Interior: take a number, see you next holiday'] },
    { type: 'prop', sprite: 'BENCH', x: 1768, y: 224 },
    { type: 'prop', sprite: 'BENCH', x: 1816, y: 224 },
    { type: 'tourist', x: 1784, y: 224 },
    { type: 'prop', sprite: 'LAMP', x: 1864, y: 224 },
    { type: 'pakid', x: 1912, y: 224 },
    { type: 'shekel', x: 1944, y: 160 },
    { type: 'shekel', x: 1960, y: 160 },
    { type: 'shekel', x: 1976, y: 160 },
    { type: 'bamba', x: 1960, y: 192 },
    { type: 'pakid', x: 2024, y: 192 },
    { type: 'pakid', x: 2136, y: 224 },
    { type: 'prop', sprite: 'MENORAH', x: 2168, y: 224 },
    { type: 'hummus', x: 2264, y: 192 },
    { type: 'sign', x: 2232, y: 224, text: ['ועדת החתולים מתכנסת. אין תור', 'The cat committee is in session. No appointments'] },
    { type: 'cat', x: 2296, y: 224 },
    { type: 'cat', x: 2344, y: 224 },
    { type: 'cat', x: 2392, y: 224 },
    { type: 'cat', x: 2440, y: 224 },
    { type: 'prop', sprite: 'BENCH', x: 2360, y: 224 },
    { type: 'prop', sprite: 'BARREL', x: 2312, y: 224 },
    { type: 'prop', sprite: 'CRATE', x: 2456, y: 224 },
    { type: 'shekel', x: 2328, y: 160 },
    { type: 'shekel', x: 2344, y: 160 },
    { type: 'shekel', x: 2360, y: 160 },
    { type: 'shekel', x: 2408, y: 160 },
    { type: 'shekel', x: 2424, y: 160 },
    { type: 'shekel', x: 2440, y: 160 },
    { type: 'pigeon', x: 2488, y: 224 },
    { type: 'sign', x: 2504, y: 224, text: ['הרכבת הקלה: "בקרוב" כבר 15 שנה', 'Light rail: "coming soon" for 15 years now'] },
    { type: 'checkpoint', x: 2536, y: 224 },
    { type: 'prop', sprite: 'OLIVE_TREE', x: 2568, y: 224 },
    { type: 'sign', x: 2600, y: 224, text: ['מחסום: תפתח את התיק. וגם את הלב', 'Checkpoint: open your bag. And your heart'] },
    { type: 'prop', sprite: 'CRATE', x: 2664, y: 224 },
    { type: 'prop', sprite: 'LAMP', x: 2680, y: 224 },
    { type: 'shekel', x: 2696, y: 160 },
    { type: 'shekel', x: 2712, y: 160 },
    { type: 'shekel', x: 2728, y: 160 },
    { type: 'falafel', x: 2776, y: 160 },
    { type: 'shekel', x: 2824, y: 160 },
    { type: 'shekel', x: 2840, y: 160 },
    { type: 'savta', x: 2904, y: 176 },
    { type: 'bamba', x: 2936, y: 160 },
    { type: 'prop', sprite: 'AWNING', x: 2920, y: 176 },
    { type: 'pigeon', x: 2888, y: 224 },
    { type: 'sign', x: 2952, y: 224, text: ['הקפיצה האחרונה לפני סבתא. תנשום', 'Last jump before Savta. Breathe'] },
    { type: 'checkpoint', x: 3064, y: 224 },
    { type: 'prop', sprite: 'OLIVE_TREE', x: 3096, y: 224 },
    { type: 'prop', sprite: 'LAMP', x: 3192, y: 224 },
    { type: 'prop', sprite: 'LAMP', x: 3384, y: 224 },
    { type: 'prop', sprite: 'MENORAH', x: 3416, y: 224 },
    { type: 'shekel', x: 3128, y: 144 },
    { type: 'shekel', x: 3144, y: 144 },
    { type: 'shekel', x: 3160, y: 144 },
    { type: 'shekel', x: 3208, y: 112 },
    { type: 'shekel', x: 3224, y: 112 },
    { type: 'shekel', x: 3240, y: 112 },
    { type: 'pigeon', x: 3256, y: 224 },
    { type: 'boss_savta', x: 3336, y: 224 },
  ],
  quips: [
    ['הרכבת הקלה מגיעה. בקרוב. מתישהו. אולי', 'The light rail is coming. Soon. Sometime. Maybe'],
    ['אבן ירושלמית: יפה, קרה, ולא סולחת', 'Jerusalem stone: beautiful, cold, and unforgiving'],
    ['לכולם פה יש דודה בקטמון', 'Everyone here has an aunt in Katamon'],
    ['החתולים לא של אף אחד. אתה של החתולים', 'The cats belong to no one. You belong to the cats'],
    ['3000 שנה ועדיין אין חניה', '3000 years and still no parking'],
    ['פקיד אמר "רגע". זה היה בחורף', 'A clerk said "one moment". That was in winter'],
    ['שווארמה עם הכל. הכל זה גם עצות מהמוכר', 'Shawarma with everything. Everything includes the vendor\'s advice'],
    ['הדודה שלך כבר יודעת שאתה פה', 'Your aunt already knows you\'re here'],
    ['יום שישי בצהריים: כולם רצים, אף אחד לא מאחר', 'Friday noon: everyone runs, nobody is late'],
    ['סבתא: "רזה". אתה: 90 קילו', 'Savta: "skinny". You: 90 kilos'],
    ['השיפוצים יסתיימו כשהמשיח יגיע. הוא בפקק', 'Renovations end when the Messiah comes. He\'s stuck in traffic'],
    ['בירושלים אומרים "בעזרת השם" גם על התור לדואר', 'In Jerusalem you say "God willing" even about the post office line'],
    ['הצפירה של שבת: הרגע היחיד שהעיר שקטה', 'The Shabbat siren: the one moment the city goes quiet'],
  ],
};
